version: '3.8'

services:
  app:
    build: .
    container_name: lojaVirtual_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: loja_BellaCase
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loja_BellaCase
      MYSQL_USER: user
      MYSQL_PASSWORD: "Severina1995"
    ports:
      - "3311:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
